using System;
using System.Collections.Generic;
using UnityEngine;

namespace GalacticScale
{
    public static partial class GS2
    {
        public static Dictionary<int, int[]> keyedLUTs = new();

        // Guards all WRITES to keyedLUTs / PatchOnUIBuildingGrid.LUT512. SetLuts is reached from
        // the main thread (CreatePlanet, OnActivePlanetLoaded) and from the planet compute/scan
        // threads via the DetermineLongitudeSegmentCount patches, and unsynchronized
        // Dictionary.Add can corrupt the table or hang a concurrent reader. Reads stay lock-free:
        // published dictionaries are never mutated again (copy-on-write below).
        private static readonly object lutLock = new();

        public static void SetLuts(int segments, float planetRadius)
        {
            // GS2.Log($"{segments}, {planetRadius}");
            if (!DSPGame.IsMenuDemo && !Vanilla) // Prevent special LUT's being created in main menu
                lock (lutLock)
            {
                if (keyedLUTs.ContainsKey(segments) && PatchOnUIBuildingGrid.LUT512.ContainsKey(segments)) return;

                // Callers disagree about planetRadius: most pass planet.radius, but the PlanetGrid
                // patch passes the segment count as the radius (it has no planet reference). Since
                // GS2 radii are always multiples of 10 (Utils.ParsePlanetSize) and segments =
                // (int)(radius / 4) * 4, each segment count maps back to exactly one radius in
                // [segments, segments + 4) - so derive it and every caller builds the identical
                // table for a given key, instead of first-write-wins deciding the geometry.
                var canonicalRadius = (segments + 9) / 10 * 10;
                if (canonicalRadius < segments + 4) planetRadius = canonicalRadius;

                if (segments < 4 || planetRadius < 5)
                {
                    planetRadius = GameMain.data.localPlanet.realRadius;
                    // (int) truncation, not CeilToInt: must match the segment-key formula used by
                    // CreatePlanet/OnActivePlanetLoaded or this fallback files its table under a
                    // key nobody else looks up.
                    segments = (int)(GameMain.data.localPlanet.radius / 4f + 0.1f) * 4;
                }
                var numSegments = segments / 4; //Number of segments on a quarter circle (the other 3/4 will result by mirroring)
                var lut = new int[numSegments];
                var segmentAngle = Mathf.PI / 2f / numSegments; //quarter circle divided by num segments is the angle per segment

                var lastMajorRadius = planetRadius;
                var lastMajorRadiusCount = numSegments * 4;

                var classicLUT = new int[512];
                classicLUT[0] = 1;
                // GS2.Warn("Start");
                for (var cnt = 0; cnt < numSegments; cnt++)
                {
                    var ringradius = Mathf.Cos(cnt * segmentAngle) * planetRadius; //cos of the nth segment is the x-distance of the point in a 2d circle
                    var classicIdx = Mathf.CeilToInt(Mathf.Abs(Mathf.Cos((float)((cnt + 1) / (segments / 4f) * Math.PI * 0.5))) * segments);

                    //If the new radius is smaller than 90% of the currently used radius, use it as the new segment count to avoid tile squishing
                    if (ringradius < 0.9 * lastMajorRadius)
                    {
                        lastMajorRadius = ringradius;
                        lastMajorRadiusCount = (int)(ringradius / 4.0) * 4;
                    }

                    lut[cnt] = lastMajorRadiusCount;
                    // Log(classicIdx.ToString());
                    if (classicIdx >= classicLUT.Length) classicIdx = classicLUT.Length - 1;
                    classicLUT[classicIdx] = lastMajorRadiusCount;
                }

                // GS2.Warn("Mid");
                var last = 1;
                for (var oldlLutIdx = 1; oldlLutIdx < 512; oldlLutIdx++)
                    if (classicLUT[oldlLutIdx] > last)
                    {
                        //Offset of 1 is required to avoid mismatch of some longitude circles
                        var temp = classicLUT[oldlLutIdx];
                        classicLUT[oldlLutIdx] = last;
                        last = temp;
                    }
                    else
                    {
                        classicLUT[oldlLutIdx] = last;
                    }

                // Warn("End");
                if (segments == 200)
                {
                    lut = new[]
                    {
                        // 4, 8, 16, 20, 32, 32, 40, 40, 60, 60, 60, 80, 80, 80, 100, 100, 100, 100, 100, 120, 120, 120,
                        // 120, 120, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 200, 200, 200, 200, 200, 200, 200,
                        // 200, 200, 200, 200, 200, 200, 200, 200, 200

                        200, 200, 200, 200, 200, 200, 200,
                        200, 200, 200, 200, 200, 200, 200, 200, 200, 160, 160, 160, 160, 160, 160, 160, 160, 160, 160, 120, 120,
                        120, 120, 120, 100, 100, 100, 100, 100, 80, 80, 80, 60, 60, 60, 40, 40, 32, 32, 20, 16, 8, 4
                    };
                    classicLUT = new int[512]
                    {
                        1,
                        4,
                        4,
                        4,
                        4,
                        4,
                        4,
                        4,
                        8,
                        8,
                        8,
                        8,
                        8,
                        8,
                        8,
                        8,
                        16,
                        16,
                        16,
                        16,
                        20,
                        20,
                        20,
                        20,
                        20,
                        20,
                        20,
                        20,
                        32,
                        32,
                        32,
                        32,
                        32,
                        32,
                        32,
                        32,
                        32,
                        32,
                        32,
                        32,
                        40,
                        40,
                        40,
                        40,
                        40,
                        40,
                        40,
                        40,
                        40,
                        40,
                        40,
                        40,
                        40,
                        40,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        60,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        80,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        100,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        120,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        160,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        200,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        240,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        300,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        400,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500,
                        500
                    };
                }

                //Fill all Look Up Tables (Dictionaries really). Publish copy-on-write: readers on
                //other threads index these without taking lutLock, so a published dictionary must
                //never be mutated - swap in a superset copy instead. Entries only ever accumulate,
                //so a reader holding a stale reference just re-checks ContainsKey and lands here.
                if (!keyedLUTs.ContainsKey(segments))
                    keyedLUTs = new Dictionary<int, int[]>(keyedLUTs) { { segments, lut } };
                if (!PatchOnUIBuildingGrid.LUT512.ContainsKey(segments))
                    PatchOnUIBuildingGrid.LUT512 = new Dictionary<int, int[]>(PatchOnUIBuildingGrid.LUT512) { { segments, classicLUT } };
            }
        }
    }
}